replicaCount: 1

image:
  repository: public.ecr.aws/aws-containers/retail-store-sample-checkout
  pullPolicy: IfNotPresent
  tag: "1.2.2"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: "checkout"

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false

metrics:
  enabled: false

app:
  persistence:
    provider: in-memory
  endpoints:
    orders: http://orders:80

redis:
  create: false

opentelemetry:
  enabled: false

podDisruptionBudget:
  enabled: false
