replicaCount: 1

image:
  repository: public.ecr.aws/aws-containers/retail-store-sample-catalog
  pullPolicy: IfNotPresent
  tag: "1.2.2"

imagePullSecrets: []
fullnameOverride: "catalog"

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false

metrics:
  enabled: false

app:
  persistence:
    provider: in-memory

# ‚ùå disable mysql
mysql:
  create: false

opentelemetry:
  enabled: false

podDisruptionBudget:
  enabled: false
