replicaCount: 1

image:
  repository: public.ecr.aws/aws-containers/retail-store-sample-orders
  pullPolicy: IfNotPresent
  tag: "1.2.2"

imagePullSecrets: []
fullnameOverride: "orders"

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false

metrics:
  enabled: false

app:
  persistence:
    provider: in-memory
  messaging:
    provider: in-memory

# ‚ùå disable infra
postgresql:
  create: false

rabbitmq:
  create: false

opentelemetry:
  enabled: false

podDisruptionBudget:
  enabled: false
